name: SwiftLint

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  lint:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Run SwiftLint with reviewdog
        uses: reviewdog/action-reviewdog@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tool_name: swiftlint
          reporter: github-pr-review
          level: warning
          filter_mode: diff_context
          fail_on_error: false
          run: |
            swiftlint lint --quiet
